version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data
  
  user-service:
    build: ./UserService
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data: